app/urls.py
from django.urls import path
from . import views

app_name = 'app'

urlpatterns = [
    
    path('services/', views.service, name='service'),
    path('shoplist/', views.shoplist, name='shoplist'),
]

blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    
    path('', views.index, name='index'),
    path('article/<int:article_id>', views.article, name='article'), 
]

mainapp/urls.py
from django.urls import path
from . import views

app_name = 'mainapp'

urlpatterns = [
    
    path('', views.index, name='index'),
    path('privacy-policy/', views.privacy, name='privacy'),
    path('tnc/', views.tnc, name='tnc'),
    path('download/', views.download, name='download'),
    path('comming-soon/', views.comming, name='comming'),
    path('contact/', views.index, name='indexc'), 
    path('merchantcontact/', views.index, name='indexmc'),
    path('merchants-list/', views.merchant, name='merchant'),
    path('music/', views.music, name='music'),
    path('quiz/', views.quizcat, name='quizcat'),
    path('quiz/<str:category_name>/', views.sets, name='sets'),
    path('quiz/set/<int:set_id>/', views.quiz, name='quiz'),
]

mystartup/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    
    path('', include('mainapp.urls')),
    path('blog/', include('blog.urls')),
    path('', include('app.urls')),
]

blog/models.py
from django.db import models

class Category(models.Model):
    category_id = models.IntegerField(primary_key=True)
    category_name = models.CharField(max_length=500)
    
    def __str__(self):
        return self.category_name

class Article(models.Model):
    article_id = models.IntegerField(primary_key=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    article_text = models.TextField(blank=True, null=True)
    article_text2 = models.TextField(blank=True, null=True)
    article_text3 = models.TextField(blank=True, null=True)
    article_title = models.CharField(max_length=500, null=True)
    article_logo = models.CharField(max_length=500, null=True)
    author = models.CharField(max_length=500, null=True)
    author_profile_link = models.CharField(max_length=500, null=True)
    date = models.CharField(max_length=500, null=True)
    article_summary = models.CharField(max_length=50000, null=True)

    def __str__(self):
        return self.article_title

class Trending(models.Model):
    article_id = models.IntegerField(primary_key=True)
    trending_title = models.CharField(max_length=500, null=True)
    trending_logo = models.CharField(max_length=500, null=True)
    trending_date = models.CharField(max_length=500, null=True)
    trending_url = models.IntegerField()

    def __str__(self):
        return self.trending_title

class Homec(models.Model):
    homec_id = models.IntegerField(primary_key=True)
    homec_title = models.CharField(max_length=500, null=True)
    homec_logo = models.CharField(max_length=500, null=True)
    homec_url = models.IntegerField()

    def __str__(self):
        return self.homec_title

class Homel(models.Model):
    homel_id = models.IntegerField(primary_key=True)
    homel_title = models.CharField(max_length=500, null=True)
    homel_logo = models.CharField(max_length=500, null=True)
    homel_date = models.CharField(max_length=500, null=True)
    homel_url = models.IntegerField()

    def __str__(self):
        return self.homel_title

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Article, Category, Trending, Homec, Homel
from mainapp.forms import FeedbackForm, MerchantFeedbackForm

def index(request):
    all_articles = Article.objects.all().order_by("article_id").reverse()
    variable = 'NOGOZO | Entertainment'
    seoimage = 'https://raw.githubusercontent.com/anuj6299/ecomfiles/master/nogozopreview.jpg'
    seodescription = "India's First Local Market E-Commerce Company"
    seotitle = 'NOGOZO | Entertainment'
    trending = Trending.objects.all().reverse()
    homel = Homel.objects.all().reverse()
    homec = Homec.objects.all().reverse()
    if request.method == 'POST':
        form = FeedbackForm(request.POST)
 
        if form.is_valid():
            form.save()
    else:
        form = FeedbackForm()
    context = {
        'all_articles' : all_articles,
        'variable' : variable,
        'seoimage' : seoimage,
        'seodescription' : seodescription,
        'seotitle' : seotitle,
        'trending' : trending,
        'homec' : homec,
        'homel' : homel,
        'form' : form,
     }
    return render(request, 'blog/index.html', context)

def article(request, article_id):
    article = Article.objects.get(article_id=article_id)
    trending = Trending.objects.all()
    variable = article.article_title+' | NOGOZO'
    seoimage = article.article_logo
    seodescription = article.article_summary
    seotitle = article.article_title
    if request.method == 'POST':
        form = FeedbackForm(request.POST)
 
        if form.is_valid():
            form.save()
    else:
        form = FeedbackForm()

    if article.article_id == 1:
        nid = 7
        pid = 6
    elif article.article_id == 2:
        nid = 9
        pid = 8
    else:
        nid = article.article_id -1
        pid = article.article_id -2
    next_article = Article.objects.get(article_id = nid)
    previous_article = Article.objects.get(article_id = pid)

    context = {
        'article' : article,
        'variable' : variable,
        'seoimage' : seoimage,
        'seodescription' : seodescription,
        'seotitle' : seotitle,
        'previous_article': previous_article,
        'next_article': next_article,
        'trending' : trending,
        'form' : form,
     }
    return render(request, 'blog/article.html', context)

blog/templates/blog/article.html
{% extends 'blog/base.html' %}
{% load static %}
{% block body %}

<br><br><br><br>
<div class="container">
    <div class="row">
        <div class="col-lg-8 col-md-12 col-sm-12 col-xs-12">
            <div class="text-container">
                <h1 style="margin-bottom: 15px; font-size: 2rem;"><b>{{article.article_title}}</b></h1>
                <h6 style= "margin-bottom: 10px; font-size: 0.9rem;"><i class="fas fa-pen-nib"></i> <a href="{{article.author_profile_link}}" style="color: black;">{{article.author}}</a> &nbsp; <i class="fas fa-clock"></i> {{article.date}}</h6>

            <img src="{{article.article_logo}}" style='height: 100%; width: 100%; border-radius: 2px; margin-top: 15px; margin-bottom: 15px; object-fit: contain' /> 
         
            <p style="font-size: 1rem;">{{ article.article_text|safe|linebreaks }}</p>
            <p style="font-size: 1rem;">{{ article.article_text2|safe|linebreaks }}</p>
            <p style="font-size: 1rem;">{{ article.article_text3|safe|linebreaks }}</p>
                
            </div> 

            <br>
            <div class="card" style="background-color: white; opacity: 70%; box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2);">
                <div class="card-body">
                    <div class="container" style="display: flex;" >
                        <div style=" flex: 1; padding: 0 10px 0 0; text-align: left; float: left; border-right: 1px solid #dedede; " >
                            <a href="{% url 'blog:article' article_id=previous_article.article_id %}" style="text-decoration: none;">
                            <p style="color: black; font-size: 1rem;"><b>Previous</b></p>
                            <p style="color: black; font-size: 1rem;">{{previous_article.article_title}}</p> </a>
                        </div>
                        <div style=" flex: 1; padding: 0 0 0 10px; text-align: right; float: right;" >
                            <a href="{% url 'blog:article' article_id=next_article.article_id %}" style="text-decoration: none;">
                            <p style="color: black; font-size: 1rem;"><b>Next</b></p>
                            <p style="color: black; font-size: 1rem;">{{next_article.article_title}}</p></a>
                        </div>
                </div>
                </div>
              </div>
              <br> <br>
        </div> 
        
        <div class="col-lg-4 col-md-12 col-sm-12 col-xs-12">
                <p style="font-size: 1.6rem; margin-bottom: 0rem;"><b>Trending Blogs</b></p> <hr style="border-top: 1px solid black;">
                {% for trending in trending %}
                <div class="row">
                        <div class="col" style="position: relative; padding-right: 0rem; padding-bottom: 1rem;">
                        <a href="{% url 'blog:article' article_id=trending.trending_url %}" style="text-decoration: none; color: black;">
                        <img src="{{trending.trending_logo}}" style="height: 100%; width: 100%; border-radius: 2px; object-fit: contain"> 
                        </div></a>
                        <div class="col" style="position: relative; padding-right: 0.5rem;"><!-- container with position relative -->
                        <a href="{% url 'blog:article' article_id=trending.trending_url %}" style="text-decoration: none; color: black;">
                        <p style="font-size: 1.1rem; margin-bottom: 0rem;"><b>{{trending.trending_title}}</b></p>   
                        <p style="font-size: 0.8rem;"><b>Date: {{trending.trending_date}}</b></p>  </a>
                        </div>      
                </div>
                {% endfor %}
        </div>
    </div> 
</div>

</div>

<style>

</style>
    {% endblock %}

blog/templates/blog/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  {% load static %}
  {% load crispy_forms_tags %}
  <title>{{variable}}</title>
  <meta content="width=device-width, initial-scale=1.0" name="viewport">
  <meta name="description" content="India's First Local Market E-Commerce Company">
  <meta name="keywords" content="shops near me, online groceries,order online,free delivery,agra local market,daily needs,trending blogs,e-commerce,home businesses,agra,trending blogs,agra news, order daily needs online,shopping, doorstep delivery">
  <meta name="author" content="Anuj Sharma">
  <meta property="og:site_name" content="NOGOZO" /> <!-- website name -->
  <meta property="og:site" content="www.nogozo.com" /> <!-- website link -->
  <meta property="og:title" content="NOGOZO"/> <!-- title shown in the actual shared post -->
  <meta property="og:description" content="India's First Local Market E-Commerce Company" /> <!-- description shown in the actual shared post -->
  <meta property="og:image" content="{% static 'mainapp/images/logo.jpg' %}" /> <!-- image link, make sure it's jpg -->
  <meta property="og:url" content="" /> <!-- where do you want your post to link to -->
  <meta property="og:type" content="article" />

  <link rel="stylesheet" type="text/css" href="{% static 'mainapp/lib/bootstrap/css/bootstrap.min.css' %}"/>
  <link rel="stylesheet" type="text/css" href="{% static 'mainapp/lib/font-awesome/css/font-awesome.min.css' %}"/>
  <link rel="stylesheet" type="text/css" href="{% static 'mainapp/lib/animate/animate.min.css' %}"/>
  <link rel="stylesheet" type="text/css" href="{% static 'mainapp/lib/ionicons/css/ionicons.min.css' %}"/>
  <link rel="stylesheet" type="text/css" href="{% static 'mainapp/lib/owlcarousel/assets/owl.carousel.min.css' %}"/>
  <link rel="stylesheet" type="text/css" href="{% static 'mainapp/lib/lightbox/css/lightbox.min.css' %}"/>
  <link rel="stylesheet" type="text/css" href="{% static 'mainapp/css/style.css' %}"/>
  
  <script src="{% static 'mainapp/js/main.js' %}"></script>
  <script src="{% static 'mainapp/lib/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'mainapp/lib/jquery/jquery-migrate.min.js' %}"></script>
  <script src="{% static 'mainapp/lib/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'mainapp/lib/easing/easing.min.js' %}"></script>
  <script src="{% static 'mainapp/lib/mobile-nav/mobile-nav.js' %}"></script>
  <script src="{% static 'mainapp/lib/wow/wow.min.js' %}"></script>
  <script src="{% static 'mainapp/lib/waypoints/waypoints.min.js' %}"></script>
  <script src="{% static 'mainapp/lib/counterup/counterup.min.js' %}"></script>
  <script src="{% static 'mainapp/lib/owlcarousel/owl.carousel.min.js' %}"></script>
  <script src="{% static 'mainapp/lib/isotope/isotope.pkgd.min.js' %}"></script>
  <script src="{% static 'mainapp/lib/lightbox/js/lightbox.min.js' %}"></script>
  <script src="{% static 'mainapp/contactform/contactform.js' %}"></script>
  
  <!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-172442704-1"></script>
<script>
window.dataLayer = window.dataLayer || [];
function gtag(){dataLayer.push(arguments);}
gtag('js', new Date());

gtag('config', 'UA-172442704-1');
</script>

  <!-- Favicons -->
  <link href="{% static 'mainapp/img/logo.jpg' %}" rel="icon">
  <link href="{% static 'mainapp/img/logo.jpg' %}" rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,500,600,700,700i|Montserrat:300,400,500,600,700" rel="stylesheet">

</head>

<body>
    <header id="header">
    <!--    <div id="topbar">
          <div class="container">
            <div class="social-links">
              <a href="https://www.facebook.com/nogozoofficial/" class="facebook"><i class="fa fa-facebook"></i></a>
              <a href="https://www.linkedin.com/company/nogozocare/" class="linkedin"><i class="fa fa-linkedin"></i></a>
              <a href="https://www.instagram.com/nogozocare/" class="instagram"><i class="fa fa-instagram"></i></a>
            </div>
          </div>
        </div> -->
    
        <div class="container">   
          <div class="logo float-left" style="display: inline-block;">
            <!-- Uncomment below if you prefer to use an image logo -->
           <a href="{% url 'mainapp:index' %}" class="scrollto"><img src="{% static 'mainapp/img/logo.png' %}" style="max-height: 2.75rem; margin: 0rem;" alt="nogozo" class="img-fluid"></a> 
           <!-- <h1 class="text-light"><a href="{% url 'mainapp:index' %}" class="scrollto"><span><b>NOGOZO</b></span></a></h1> -->
          </div>   
          <nav class="main-nav float-right d-none d-lg-block">
            <ul>
              <li class="active"><a href="{% url 'mainapp:index' %}">Home</a></li>
              <li><a href="{% url 'mainapp:index' %}#pricing">Features</a></li>
              <li><a href="{% url 'mainapp:index' %}#services">Services</a></li>
              <li class="drop-down"><a href="">Fun Zone</a>
                <ul>
                  <li><a href="{% url 'blog:index' %}">Blogs</a></li>
                  <li><a href="{% url 'mainapp:music' %}">Music</a></li>
                  <li><a href="{% url 'mainapp:quizcat' %}">Trivia Quiz</a></li>
                </ul>
              </li>
              <li><a href="#footer">Contact Us</a></li>
            </ul>
          </nav><!-- .main-nav -->         
        </div>
      </header>

  {% block body %}
  {% endblock %}
  
  <footer id="footer" class="section-bg">
    <div class="footer-top">
      <div class="container">
        <div class="row">
          <div class="col-lg-6">
            <div class="row">
                <div class="col-sm-6">
                  <div class="footer-info">
                    <h3>About Us</h3>
                    <p>NOGOZO is India’s First Advanced Local E-Market Platform which provides its user advantages of online shopping with the trust of local merchants. 
                      NOGOZO provides its users with a plethora of advanced features and valuable multifunctional assets for its Buyers, Merchants, Servicemen, and home businesses</p>
                    <br> <p>We are a community that aims to build a comfortable and health-conscious market environment. We dream to create an online marketing platform that maximizes the profit and comfort of both our consumers and retailers.
                      </p>
                  </div>
                </div>
                <div class="col-sm-6">
                  <div class="footer-links">
                    <h4>Useful Links</h4>
                    <ul>
                      <li><a href="{% url 'mainapp:index' %}">Home</a></li>
                      <li><a href="{% url 'mainapp:index' %}#pricing">Features</a></li>
                      <li><a href="{% url 'mainapp:index' %}#services">Services</a></li>
                      <li><a href="{% url 'blog:index' %}">Blogs</a></li>
                      <li><a href="{% url 'mainapp:merchant' %}">Merchants</a></li>
                      <li><a href="{% url 'mainapp:tnc' %}">Terms of service</a></li>
                      <li><a href="{% url 'mainapp:privacy' %}">Privacy policy</a></li>
                    </ul>
                  </div>
                  <div class="footer-links">
                    <h4>Contact Us</h4>
                    
                      <strong>Phone:</strong> +91 8456787667<br>
                      <strong>Email:</strong> contact@nogozo.com<br>
                    
                  </div>
                  <div class="social-links">
                    <a href="https://www.facebook.com/nogozoofficial/" class="facebook"><i class="fa fa-facebook"></i></a>
                    <a href="https://www.linkedin.com/company/nogozocare/" class="linkedin"><i class="fa fa-linkedin"></i></a>
                    <a href="https://www.instagram.com/nogozocare/" class="instagram"><i class="fa fa-instagram"></i></a>
                  </div>
                </div>
            </div>
          </div>

          <div class="col-lg-6">
            <div class="form">              
              <h4>Send us a message</h4>
              <form action="{% url 'mainapp:index' %}" method="POST">
                {% csrf_token %}
                {{ form|crispy }}
                <div id="sendmessage">Your message has been sent. Thank you!</div>
                <div id="errormessage"></div>
                <div class="text-center"><button type="submit" title="Send Message">Send Message</button></div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </footer>
  
<!--  <a href="#" class="back-to-top"><i class="fa fa-chevron-up"></i></a> -->
  <!-- Uncomment below i you want to use a preloader -->
  <!-- <div id="preloader"></div> -->
  <div class="whatsapp">
    <a href="https://api.whatsapp.com/send?text=Hello NOGOZO!&phone=918979497958">
    <img style="width: 4rem;" src="{% static 'mainapp/img/whatsapp.png' %}"> </a>
  </div>

<style>.whatsapp{position:fixed;right:0;bottom:0;margin:15px;padding:0px;width: 4rem;animation: rotation 2s infinite linear;}@keyframes rotation {from {transform: rotate(0deg);}to{transform: rotate(359deg);}}</style>


  <script src="{% static 'mainapp/js/main.js' %}"></script>
  <script src="{% static 'mainapp/lib/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'mainapp/lib/jquery/jquery-migrate.min.js' %}"></script>
  <script src="{% static 'mainapp/lib/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'mainapp/lib/easing/easing.min.js' %}"></script>
  <script src="{% static 'mainapp/lib/mobile-nav/mobile-nav.js' %}"></script>
  <script src="{% static 'mainapp/lib/wow/wow.min.js' %}"></script>
  <script src="{% static 'mainapp/lib/waypoints/waypoints.min.js' %}"></script>
  <script src="{% static 'mainapp/lib/counterup/counterup.min.js' %}"></script>
  <script src="{% static 'mainapp/lib/owlcarousel/owl.carousel.min.js' %}"></script>
  <script src="{% static 'mainapp/lib/isotope/isotope.pkgd.min.js' %}"></script>
  <script src="{% static 'mainapp/lib/lightbox/js/lightbox.min.js' %}"></script>
  <script src="{% static 'mainapp/contactform/contactform.js' %}"></script> 

  <script src="https://kit.fontawesome.com/1d8298542f.js" crossorigin="anonymous"></script>

</body>
</html>