app/urls.py
from django.urls import path
from . import views

app_name = 'app'

urlpatterns = [
    
    path('services/', views.service, name='service'),
    path('shoplist/', views.shoplist, name='shoplist'),
]

blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    
    path('', views.index, name='index'),
    path('article/<int:article_id>', views.article, name='article'), 
]

mainapp/urls.py
from django.urls import path
from . import views

app_name = 'mainapp'

urlpatterns = [
    
    path('', views.index, name='index'),
    path('privacy-policy/', views.privacy, name='privacy'),
    path('tnc/', views.tnc, name='tnc'),
    path('download/', views.download, name='download'),
    path('comming-soon/', views.comming, name='comming'),
    path('contact/', views.index, name='indexc'), 
    path('merchantcontact/', views.index, name='indexmc'),
    path('merchants-list/', views.merchant, name='merchant'),
    path('music/', views.music, name='music'),
    path('quiz/', views.quizcat, name='quizcat'),
    path('quiz/<str:category_name>/', views.sets, name='sets'),
    path('quiz/set/<int:set_id>/', views.quiz, name='quiz'),
]

mystartup/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    
    path('', include('mainapp.urls')),
    path('blog/', include('blog.urls')),
    path('', include('app.urls')),
]

mainapp/models.py
from django.db import models


class Feedback(models.Model):
    name = models.CharField(max_length=120)
    email = models.CharField(max_length=20)
    comment = models.TextField()
    
    def __str__(self):
        return self.name


class MerchantFeedback(models.Model):
    shop_name = models.CharField(max_length=120)
    contact_number = models.CharField(max_length=20)
    shop_address = models.CharField(max_length=250)
    comment = models.TextField()
    
    def __str__(self):
        return self.shop_name

class City(models.Model):
    city_id = models.IntegerField(primary_key=True)
    city_name = models.CharField(max_length=500)
    
    def __str__(self):
        return self.city_name

        
class Area(models.Model):
    area_id = models.IntegerField(primary_key=True)
    city = models.ForeignKey(City, on_delete=models.CASCADE)
    area_name = models.CharField(max_length=500)

    def __str__(self):
        return self.area_name

class Shop(models.Model):
    shop_id = models.IntegerField(primary_key=True)
    area = models.ForeignKey(Area, on_delete=models.CASCADE)
    shop_name = models.CharField(max_length=500)

    def __str__(self):
        return self.shop_name

class Item(models.Model):
    item_id = models.IntegerField(primary_key=True)
    shop = models.ForeignKey(Shop, on_delete=models.CASCADE)
    item_name = models.CharField(max_length=500)

    def __str__(self):
        return self.item_name

class Merchant(models.Model):
    shop_id = models.IntegerField(primary_key=True)
    shop_name = models.CharField(max_length=500)
    shop_address = models.CharField(max_length=500)
    shop_image = models.CharField(max_length=500)

    def __str__(self):
        return self.shop_name

class Category(models.Model):
    category_id = models.IntegerField(primary_key=True)
    category_name = models.CharField(max_length=500)
    
    def __str__(self):
        return self.category_name

class Sets(models.Model):
    set_id = models.IntegerField(primary_key=True)
    set_topic = models.CharField(max_length=500)
    set_date = models.CharField(max_length=500)
    set_category = models.ForeignKey(Category, on_delete=models.CASCADE)

    set_question1 = models.CharField(max_length=500)
    set_option1a = models.CharField(max_length=500)
    set_option1b = models.CharField(max_length=500)
    set_option1c = models.CharField(max_length=500)
    set_answer1 = models.CharField(max_length=500)
    set_img1 = models.CharField(max_length=500)

    set_question2 = models.CharField(max_length=500)
    set_option2a = models.CharField(max_length=500)
    set_option2b = models.CharField(max_length=500)
    set_option2c = models.CharField(max_length=500)
    set_answer2 = models.CharField(max_length=500)
    set_img2 = models.CharField(max_length=500)

    set_question3 = models.CharField(max_length=500)
    set_option3a = models.CharField(max_length=500)
    set_option3b = models.CharField(max_length=500)
    set_option3c = models.CharField(max_length=500)
    set_answer3 = models.CharField(max_length=500)
    set_img3 = models.CharField(max_length=500)

    set_question4 = models.CharField(max_length=500)
    set_option4a = models.CharField(max_length=500)
    set_option4b = models.CharField(max_length=500)
    set_option4c = models.CharField(max_length=500)
    set_answer4 = models.CharField(max_length=500)
    set_img4 = models.CharField(max_length=500)

    set_question5 = models.CharField(max_length=500)
    set_option5a = models.CharField(max_length=500)
    set_option5b = models.CharField(max_length=500)
    set_option5c = models.CharField(max_length=500)
    set_answer5 = models.CharField(max_length=500)
    set_img5 = models.CharField(max_length=500)

    def __str__(self):
        return self.set_topic

mainapp/forms.py
from django import forms
from crispy_forms.helper import FormHelper
from .models import Feedback, MerchantFeedback

 
class FeedbackForm(forms.ModelForm):
    helper = FormHelper()

    class Meta:
        model = Feedback
        fields = "__all__"


class MerchantFeedbackForm(forms.ModelForm):
    helper = FormHelper()

    class Meta:
        model = MerchantFeedback
        fields = "__all__"

mainapp/views.py
from django.shortcuts import render, get_object_or_404
from .forms import FeedbackForm, MerchantFeedbackForm
from .models import Feedback, MerchantFeedback, Merchant, Category, Sets
from blog.models import Article
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

def index(request):
    if request.method == 'POST':
        form = FeedbackForm(request.POST)
 
        if form.is_valid():
            form.save()
    else:
        form = FeedbackForm()
    return render(request, 'mainapp/index.html', {'form': form})


def privacy(request):
    if request.method == 'POST':
        form = FeedbackForm(request.POST)
 
        if form.is_valid():
            form.save()
            return render(request, 'mainapp/thanks.html', context)
    else:
        form = FeedbackForm()    
    context = {
    }
    return render(request, 'mainapp/privacy.html', {'form': form} )


def tnc(request):
    if request.method == 'POST':
        form = FeedbackForm(request.POST)
 
        if form.is_valid():
            form.save()
            return render(request, 'mainapp/thanks.html', context)
    else:
        form = FeedbackForm()    
    context = {
    }
    return render(request, 'mainapp/tnc.html', {'form': form} )


def comming(request):
    if request.method == 'POST':
        form = FeedbackForm(request.POST)
 
        if form.is_valid():
            form.save()
            return render(request, 'mainapp/thanks.html', context)
    else:
        form = FeedbackForm()    
    context = {
    }
    return render(request, 'mainapp/comming.html', {'form': form} )


def download(request):
    if request.method == 'POST':
        form = FeedbackForm(request.POST)
 
        if form.is_valid():
            form.save()
    else:
        form = FeedbackForm()
    return render(request, 'mainapp/download.html', {'form': form})

 
def contact(request): 
    all_articles = Article.objects.all().order_by("article_id").reverse()
    context = {
        'all_articles' : all_articles,
     }
    if request.method == 'POST':
        form = FeedbackForm(request.POST)
 
        if form.is_valid():
            form.save()
            return render(request, 'mainapp/thanks.html', context)
    else:
        form = FeedbackForm()
    return render(request, 'mainapp/contact.html', {'form': form})

 
def merchantcontact(request):
    all_articles = Article.objects.all().order_by("article_id").reverse()
    context = {
        'all_articles' : all_articles,
     }    
    if request.method == 'POST':
        form = MerchantFeedbackForm(request.POST)
 
        if form.is_valid():
            form.save()
            return render(request, 'mainapp/thanks.html', context)
    else:
        form = MerchantFeedbackForm()
    return render(request, 'mainapp/merchantcontact.html', {'form': form})

# def merchant(request):
#     shop = Merchant.objects.all()
#     context = {
#         'shop' : shop,
#     }
#     if request.method == 'POST':
#         form = FeedbackForm(request.POST)
 
#         if form.is_valid():
#             form.save()
#             return render(request, 'mainapp/thanks.html', context)
#     else:
#         form = FeedbackForm()    
#     return render(request, 'mainapp/merchant.html', {'form': form}, context )

def merchant(request):
    shop = Merchant.objects.all()
    page = request.GET.get('page', 1)

    paginator = Paginator(shop, 5)
    try:
        shops = paginator.page(page)
    except PageNotAnInteger:
        shops = paginator.page(1)
    except EmptyPage:
        shops = paginator.page(paginator.num_pages)

    if request.method == 'POST':
        form = FeedbackForm(request.POST)
 
        if form.is_valid():
            form.save()
    else:
        form = FeedbackForm()
    context = {
        'shop' : shop,
        'form' : form,
        'shops' : shops,
     }
    return render(request, 'mainapp/merchant.html', context)

def music(request):
    if request.method == 'POST':
        form = FeedbackForm(request.POST)
 
        if form.is_valid():
            form.save()
    else:
        form = FeedbackForm()
    context = {
        'form' : form,
     }
    return render(request, 'mainapp/music.html', context)

def quizcat(request):
    all_category = Category.objects.all()
    if request.method == 'POST':
        form = FeedbackForm(request.POST)
 
        if form.is_valid():
            form.save()
    else:
        form = FeedbackForm()
    context = {
        'form' : form,
        'all_category' : all_category
     }
    return render(request, 'mainapp/quizcat.html', context)

def sets(request,category_name):
    category = Category.objects.get(category_name=category_name)
    all_category = Category.objects.all()
    all_set = Sets.objects.all()
    if request.method == 'POST':
        form = FeedbackForm(request.POST)
 
        if form.is_valid():
            form.save()
    else:
        form = FeedbackForm()
    context = {
        'all_category' : all_category,
        'category' : category,    
        'all_set' : all_set,
        'form' : form,
     }
    return render(request, 'mainapp/sets.html', context)
    
def quiz(request,set_id):
    all_category = Category.objects.all()
    set_info = Sets.objects.get(set_id = set_id)
    if set_id == Sets.objects.all().count():
        next_id = 1
    else:
        next_id = set_id+ 1

    if request.method == 'POST':
        form = FeedbackForm(request.POST)
 
        if form.is_valid():
            form.save()
    else:
        form = FeedbackForm()   
    context = {
        'all_category' : all_category,
        'set_info' : set_info, 
        'next_id' : next_id, 
        'form' : form  
    }
    return render(request, 'mainapp/quiz.html', context )

mainapp/templates/mainapp/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>NOGOZO</title>
  {% load static %}
  {% load crispy_forms_tags %}
  <meta content="width=device-width, initial-scale=1.0" name="viewport">
  <meta name="description" content="India's First Local Market E-Commerce Company">
  <meta name="keywords" content="shops near me, online groceries,order online,free delivery,agra local market,daily needs,trending blogs,e-commerce,home businesses,agra,trending blogs,agra news, order daily needs online,shopping, doorstep delivery">
  <meta name="author" content="Anuj Sharma">
  <meta property="og:site_name" content="NOGOZO" /> <!-- website name -->
  <meta property="og:site" content="www.nogozo.com" /> <!-- website link -->
  <meta property="og:title" content="NOGOZO"/> <!-- title shown in the actual shared post -->
  <meta property="og:description" content="India's First Local Market E-Commerce Company" /> <!-- description shown in the actual shared post -->
  <meta property="og:image" content="{% static 'mainapp/images/logo.jpg' %}" /> <!-- image link, make sure it's jpg -->
  <meta property="og:url" content="" /> <!-- where do you want your post to link to -->
  <meta property="og:type" content="article" />

  <link rel="stylesheet" type="text/css" href="{% static 'mainapp/lib/bootstrap/css/bootstrap.min.css' %}"/>
  <link rel="stylesheet" type="text/css" href="{% static 'mainapp/lib/font-awesome/css/font-awesome.min.css' %}"/>
  <link rel="stylesheet" type="text/css" href="{% static 'mainapp/lib/animate/animate.min.css' %}"/>
  <link rel="stylesheet" type="text/css" href="{% static 'mainapp/lib/ionicons/css/ionicons.min.css' %}"/>
  <link rel="stylesheet" type="text/css" href="{% static 'mainapp/lib/owlcarousel/assets/owl.carousel.min.css' %}"/>
  <link rel="stylesheet" type="text/css" href="{% static 'mainapp/lib/lightbox/css/lightbox.min.css' %}"/>
  <link rel="stylesheet" type="text/css" href="{% static 'mainapp/css/style.css' %}"/>
  
  <script src="{% static 'mainapp/js/main.js' %}"></script>
  <script src="{% static 'mainapp/lib/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'mainapp/lib/jquery/jquery-migrate.min.js' %}"></script>
  <script src="{% static 'mainapp/lib/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'mainapp/lib/easing/easing.min.js' %}"></script>
  <script src="{% static 'mainapp/lib/mobile-nav/mobile-nav.js' %}"></script>
  <script src="{% static 'mainapp/lib/wow/wow.min.js' %}"></script>
  <script src="{% static 'mainapp/lib/waypoints/waypoints.min.js' %}"></script>
  <script src="{% static 'mainapp/lib/counterup/counterup.min.js' %}"></script>
  <script src="{% static 'mainapp/lib/owlcarousel/owl.carousel.min.js' %}"></script>
  <script src="{% static 'mainapp/lib/isotope/isotope.pkgd.min.js' %}"></script>
  <script src="{% static 'mainapp/lib/lightbox/js/lightbox.min.js' %}"></script>
  <script src="{% static 'mainapp/contactform/contactform.js' %}"></script>
  
  <!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-172442704-1"></script>
<script>
window.dataLayer = window.dataLayer || [];
function gtag(){dataLayer.push(arguments);}
gtag('js', new Date());

gtag('config', 'UA-172442704-1');
</script>

  <!-- Favicons -->
  <link href="{% static 'mainapp/img/favicon.png' %}" rel="icon">
  <link href="{% static 'mainapp/img/favicon.png' %}" rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,500,600,700,700i|Montserrat:300,400,500,600,700" rel="stylesheet">

</head>

<body>
    <header id="header">
    <!--    <div id="topbar">
          <div class="container">
            <div class="social-links">
              <a href="https://www.facebook.com/nogozoofficial/" class="facebook"><i class="fa fa-facebook"></i></a>
              <a href="https://www.linkedin.com/company/nogozocare/" class="linkedin"><i class="fa fa-linkedin"></i></a>
              <a href="https://www.instagram.com/nogozocare/" class="instagram"><i class="fa fa-instagram"></i></a>
            </div>
          </div>
        </div> -->
    
        <div class="container">   
          <div class="logo float-left" style="display: inline-block;">
            <!-- Uncomment below if you prefer to use an image logo -->
           <a href="{% url 'mainapp:index' %}" class="scrollto"><img src="{% static 'mainapp/img/logo.png' %}" style="max-height: 2.75rem; margin: 0rem;" alt="nogozo" class="img-fluid"></a> 
           <!-- <h1 class="text-light"><a href="{% url 'mainapp:index' %}" class="scrollto"><span><b>NOGOZO</b></span></a></h1> -->
          </div>   
          <nav class="main-nav float-right d-none d-lg-block">
            <ul>
              <li class="active"><a href="{% url 'mainapp:index' %}">Home</a></li>
              <li><a href="{% url 'mainapp:index' %}#pricing">Features</a></li>
              <li><a href="{% url 'mainapp:index' %}#services">Services</a></li>
              <li class="drop-down"><a href="">Fun Zone</a>
                <ul>
                  <li><a href="{% url 'blog:index' %}">Blogs</a></li>
                  <li><a href="{% url 'mainapp:music' %}">Music</a></li>
                  <li><a href="{% url 'mainapp:quizcat' %}">Trivia Quiz</a></li>
                </ul>
              </li>
              <li><a href="{% url 'mainapp:merchant' %}">Merchants</a></li>
              <li><a href="#footer">Contact Us</a></li>
            </ul>
          </nav>       
        </div>
      </header>

  {% block body %}
  {% endblock %}
  
  <footer id="footer" class="section-bg">
    <div class="footer-top">
      <div class="container">
        <div class="row">
          <div class="col-lg-6">
            <div class="row">
                <div class="col-sm-6">
                  <div class="footer-info">
                    <h3>About Us</h3>
                    <p>NOGOZO is India’s First Advanced Local E-Market Platform which provides its user advantages of online shopping with the trust of local merchants. 
                      NOGOZO provides its users with a plethora of advanced features and valuable multifunctional assets for its Buyers, Merchants, Servicemen, and home businesses</p>
                    <br> <p>We are a community that aims to build a comfortable and health-conscious market environment. We dream to create an online marketing platform that maximizes the profit and comfort of both our consumers and retailers.
                      </p>
                  </div>
                </div>
                <div class="col-sm-6">
                  <div class="footer-links">
                    <h4>Useful Links</h4>
                    <ul>
                      <li><a href="{% url 'mainapp:index' %}">Home</a></li>
                      <li><a href="{% url 'mainapp:index' %}#pricing">Features</a></li>
                      <li><a href="{% url 'mainapp:index' %}#services">Services</a></li>
                      <li><a href="{% url 'blog:index' %}">Blogs</a></li>
                      <li><a href="{% url 'mainapp:merchant' %}">Merchants</a></li>
                      <li><a href="{% url 'mainapp:tnc' %}">Terms of service</a></li>
                      <li><a href="{% url 'mainapp:privacy' %}">Privacy policy</a></li>
                    </ul>
                  </div>
                  <div class="footer-links">
                    <h4>Contact Us</h4>
                      <strong>Phone:</strong> +91 8979497958<br>
                      <strong>Email:</strong> contact@nogozo.com<br>                  
                  </div>
                  <div class="social-links">
                    <a href="https://www.facebook.com/nogozoofficial/" class="facebook"><i class="fa fa-facebook"></i></a>
                    <a href="https://www.linkedin.com/company/nogozocare/" class="linkedin"><i class="fa fa-linkedin"></i></a>
                    <a href="https://www.instagram.com/nogozocare/" class="instagram"><i class="fa fa-instagram"></i></a>
                  </div>
                </div>
            </div>
          </div>

          <div class="col-lg-6">
            <div class="form">              
              <h4>Send us a message</h4>
              <form action="{% url 'mainapp:index' %}" method="POST">
                {% csrf_token %}
                {{ form|crispy }}
                <div id="sendmessage">Your message has been sent. Thank you!</div>
                <div id="errormessage"></div>
                <div class="text-center"><button type="submit" title="Send Message">Send Message</button></div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </footer>

  <!-- <a href="#" class="back-to-top"><i class="fa fa-chevron-up"></i></a> -->
  <!-- Uncomment below i you want to use a preloader -->
  <!-- <div id="preloader"></div> -->

 

<style>.whatsapp{position:fixed;right:0;bottom:0;margin:15px;padding:0px;width: 4rem;animation: rotation 2s infinite linear;}@keyframes rotation {from {transform: rotate(0deg);}to{transform: rotate(359deg);}}</style>

  <script src="{% static 'mainapp/js/main.js' %}"></script>
  <script src="{% static 'mainapp/lib/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'mainapp/lib/jquery/jquery-migrate.min.js' %}"></script>
  <script src="{% static 'mainapp/lib/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'mainapp/lib/easing/easing.min.js' %}"></script>
  <script src="{% static 'mainapp/lib/mobile-nav/mobile-nav.js' %}"></script>
  <script src="{% static 'mainapp/lib/wow/wow.min.js' %}"></script>
  <script src="{% static 'mainapp/lib/waypoints/waypoints.min.js' %}"></script>
  <script src="{% static 'mainapp/lib/counterup/counterup.min.js' %}"></script>
  <script src="{% static 'mainapp/lib/owlcarousel/owl.carousel.min.js' %}"></script>
  <script src="{% static 'mainapp/lib/isotope/isotope.pkgd.min.js' %}"></script>
  <script src="{% static 'mainapp/lib/lightbox/js/lightbox.min.js' %}"></script>
  <script src="{% static 'mainapp/contactform/contactform.js' %}"></script> 

  <script src="https://kit.fontawesome.com/1d8298542f.js" crossorigin="anonymous"></script>

</body>
</html>

mainapp/templates/mainapp/contact.html
{% extends 'mainapp/base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block body %}
<div class="tabs">
<br> 
<div class="container">
	<div class=" contact">
<div class="col-u">
	<div class="card-header p-0">
		<div class="bg-color text-white text-center py-2">
			<h1 style="font-size: 36px; font-family: Poppins, sans-serif; font-weight: 700;"><i class="fa fa-envelope"></i> Contact Us</h1>
			<h4 style="font-size: 18px; font-family: Poppins, sans-serif; font-weight: 700;"> We would love to hear from you!</h4>
		</div>
	</div> </div>
		<div class="col-b">
			<div class="contact-form">		
<form action="{% url 'mainapp:contact' %}" method="POST">
{% csrf_token %}
{{ form|crispy }}
<button type="submit" class="btn btn-default" value="submit">Submit</button>
</form>
			</div>
		</div>
	</div>
</div>
</div>
{% endblock %}

mainapp/templates/mainapp/quiz.html
{% extends 'mainapp/base.html' %}
{% load static %}
{% block body %}
<br> <br><br><br>
<style>.btn-space {margin-right: 10px;margin-bottom: 10px;}</style>
<div class="container">
    <div id="wrapper">
        <div class="jumbotron">
        <div class="text-center">
                <h2>{{set_info.set_category}} Quiz on {{set_info.set_topic}}</h2>  </div>
               <!-- <h3>Instructions:</h3>
                <h4>1. This trivia quiz contains 5 questions</h4>
                <h4>2. You will get 30 seconds for each question</h4>
                <h4>3. There will be 3 options for each question</h4>
                <h4>4. The result will contain number of correct answers, unattempted answers and wrong answers.</h4> <br> -->
                <div class="text-center">
                <a id="start" class="btn btn-primary btn-lg" href="#" role="button">Start!</a>
        </div> </div>
        <div id="subwrapper"> </div>
</div>
</div>
<br><br>
<script>
   
    // remove the start button when clicked
$('#start').on('click', function(){
    $('#start').remove();
  game.loadQuestion();

})

// click event when you click the answer

$(document).on('click','.answer-button',function(e){
    game.clicked(e);
})

$(document).on('click','#reset',function(){
    game.reset();
})

// Variable for questions, an array of objects 

let questions = [{
    question: "{{set_info.set_question1}}",
    answers: ["{{set_info.set_option1a}}", "{{set_info.set_option1b}}", "{{set_info.set_option1c}}"],
    correctAnswer: "{{ set_info.set_answer1 }}",
    image: "assets/images/imagename"
}, {
    question: "{{set_info.set_question2}}",
    answers: ["{{set_info.set_option2a}}", "{{set_info.set_option2b}}", "{{set_info.set_option2c}}"],
    correctAnswer: "{{ set_info.set_answer2 }}",
    image: "assets/images/imagename",
}, {
question: "{{set_info.set_question3}}",
    answers: ["{{set_info.set_option3a}}", "{{set_info.set_option3b}}", "{{set_info.set_option3c}}"],
    correctAnswer: "{{ set_info.set_answer3 }}",
    image: "assets/images/imagename",
}, {
    question: "{{set_info.set_question4}}",
    answers: ["{{set_info.set_option4a}}", "{{set_info.set_option4b}}", "{{set_info.set_option4c}}"],
    correctAnswer: "{{ set_info.set_answer4 }}",
    image: "assets/images/imagename"
}, {
    question: "{{set_info.set_question5}}",
    answers: ["{{set_info.set_option5a}}", "{{set_info.set_option5b}}", "{{set_info.set_option5c}}"],
    correctAnswer: "{{ set_info.set_answer5 }}",
    image: "assets/images/imagename"
},

];


var game = {
    questions:questions,
    currentQuestion:0, 
    counter:30, 
    correct:0,
    incorrect:0,
    unanswered:0,
    
    countdown: function(){
        game.counter --;
        $('#counter').html(game.counter); 
        if(game.counter<=0){
            console.log("TIME UP!")
            game.timeUp();
        }
    },
    loadQuestion: function (){
        timer = setInterval(game.countdown,1000);
        $('#subwrapper').html("<h5> Time to Guess: <span id ='counter'>30</span> Seconds</h5>");
        $('#subwrapper').append('<h4>'+questions[game.currentQuestion].question+'</h4>');
        for(var i=0;i<questions[game.currentQuestion].answers.length;i++){
            $('#subwrapper').append('<button class="btn btn-light btn-space answer-button" id="button- '+i+'" data-name="'+questions[game.currentQuestion].answers[i]+'">'+questions[game.currentQuestion].answers[i]+'</button>');
        }
    },
    nextQuestion: function(){
        game.counter = 30;
        $('#counter').html(game.counter);
        game.currentQuestion++;
        game.loadQuestion();

    },
    timeUp: function(){
        clearInterval(timer);
        game.unanswered++;
        $('#subwrapper').html('<h2>Out of time!<h2>');
        $('#subwrapper').append('<h4>The correct answer was: '+questions[game.currentQuestion].correctAnswer+'</h4>');
        if(game.currentQuestion==questions.length-1){
            setTimeout(game.results,3*1000);
        } else{
            setTimeout(game.nextQuestion,3*1000);
        }

    },
    results: function(){
        clearInterval(timer);
        $('#subwrapper').html('<h2>Complete!</h2>')
        $('#subwrapper').append(" Correct: " +game.correct + '<br/>');
        $('#subwrapper').append(" Incorrect: " +game.incorrect + '<br/>');
        $('#subwrapper').append(" Unanswered: " +game.unanswered + '<br/>');
        $('#subwrapper').append('<br><a href="{% url "mainapp:index" %}"><button class="btn btn-light">Home</button></a> &nbsp <a href="{% url "mainapp:quiz" set_id=next_id %}"><button class="btn btn-light">Next set</button></a>')


    },
    clicked: function(e){
        clearInterval(timer);
        if($(e.target).data("name")==questions[game.currentQuestion].correctAnswer){
            game.answeredCorrectly();
    } else {
        game.answeredIncorrectly();
    }

    },
    answeredCorrectly: function(){
        console.log("right!")
        clearInterval(timer);
        game.correct++;
        $('#subwrapper').html('<h2> CORRECT!</h2>');
        if(game.currentQuestion==questions.length-1){
            setTimeout(game.results,2*1000);
        } else{
            setTimeout(game.nextQuestion,2*1000);
        }

    },
    answeredIncorrectly: function(){
        console.log("wrong")
        clearInterval(timer);
        game.incorrect++;
        $('#subwrapper').html('<h2> Wrong!</h2>');
        $('#subwrapper').append('<h5>The correct answer was: '+questions[game.currentQuestion].correctAnswer+'</h5>');
        if(game.currentQuestion==questions.length-1){
            setTimeout(game.results,2*1000);
        } else{
            setTimeout(game.nextQuestion,2*1000);
        }

    },
    reset: function(){
        game.currentQuestion = 0;
        game.counter = 0;
        game.correct = 0;
        game.incorrect = 0;
        game.unanswered = 0;
        game.loadQuestion();

    }

}
  </script>

{% endblock %}